version: '3.8'

services:
  app:
    build: .
    command: gunicorn tinbox.wsgi --bind 0.0.0.0:8010 --workers 3
    restart: unless-stopped
    ports: 
      - "8010"
    env_file:
      - ./.env
    depends_on:
      - db
  
  nginx:
    image: nginx:alpine
    ports: 
      - "8123:80"
    volumes:
      - ./static/:/var/www/html/static/:ro
      - ./_config/default.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ./.env

  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - ./.env

volumes:
  mariadb_data: