version: '3.8'

services:
  app:
    build: .
    command: gunicorn tinbox.wsgi --bind 0.0.0.0:80 --workers 3
    restart: unless-stopped
    ports:
      - "${PORT}:80"
    volumes:
      - ./media/:/app/media
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/mysql
    env_file:
      - ./.env
